name: Scaleway Deployment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-to-scaleway:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Configure AWS CLI for Scaleway
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/config
        echo "aws_access_key_id = ${{ secrets.SCALEWAY_ACCESS_KEY }}" >> ~/.aws/config
        echo "aws_secret_access_key = ${{ secrets.SCALEWAY_SECRET_KEY }}" >> ~/.aws/config
        echo "region = fr-par" >> ~/.aws/config
        echo "output = json" >> ~/.aws/config
        aws configure set s3.endpoint_url https://s3.fr-par.scw.cloud
        - name: Verify AWS CLI Version
        run: aws --version
    - name: Configure AWS CLI for Scaleway
      run: |
        mkdir -p ~/.aws
        # Create credentials file
        cat > ~/.aws/credentials << EOF
        [default]
        aws_access_key_id = ${{ secrets.SCALEWAY_ACCESS_KEY }}
        aws_secret_access_key = ${{ secrets.SCALEWAY_SECRET_KEY }}
        EOF
        
        # Create config file
        cat > ~/.aws/config << EOF
        [default]
        region = fr-par
        EOF
    - name: Configure Rclone for Scaleway
      run: |
        mkdir -p ~/.config/rclone
        cat > ~/.config/rclone/rclone.conf << EOF
        [scaleway]
        type = s3
        provider = Other
        env_auth = false
        access_key_id = ${{ secrets.SCALEWAY_ACCESS_KEY }}
        secret_access_key = ${{ secrets.SCALEWAY_SECRET_KEY }}
        region = fr-par
        endpoint = https://s3.fr-par.scw.cloud
        acl = public-read
        EOF
    - name: Deploy to Scaleway using Rclone
      run: |
        rclone sync dist scaleway:${{ env.DEPLOY_BUCKET }} \
          --progress \
          --exclude .DS_Store \
          --exclude *.swp \
          --s3-acl=public-read