name: Scaleway Deployment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-to-scaleway:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm build
    - name: Configure AWS CLI for Scaleway
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/config
        echo "aws_access_key_id = ${{ secrets.SCALEWAY_ACCESS_KEY }}" >> ~/.aws/config
        echo "aws_secret_access_key = ${{ secrets.SCALEWAY_SECRET_KEY }}" >> ~/.aws/config
        echo "region = fr-par" >> ~/.aws/config
        echo "output = json" >> ~/.aws/config
        aws configure set s3.endpoint_url https://s3.fr-par.scw.cloud
    - name: Deploy to Scaleway
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SCALEWAY_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
      run: |
        aws s3 sync dist s3://jlbqi.com \
          --delete \
          --endpoint-url https://s3.fr-par.scw.cloud \
          --region fr-par \
          --acl public-read \
          --cache-control "max-age=86400" \
          --exclude "*.html" \
          --exclude "*.json"

        aws s3 sync dist s3://jlbqi.com \
          --delete \
          --endpoint-url https://s3.fr-par.scw.cloud \
          --region fr-par \
          --acl public-read \
          --cache-control "no-cache, no-store, must-revalidate" \
          --include "*.html" \
          --include "*.json"
